name: fatiando-data-bushveld-gravity
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - numpy
  - jupyterlab
  - xarray
  - netcdf4
  - pyproj
  # PyGMT for plotting
  - pygmt==0.4.1
  - gmt==6.2.0
  # Fatiando
  - pooch>=1.0
  - ensaio>=0.3.0
  - boule==0.3.*
  - harmonica==0.4.*
  - verde==1.7.*
  - boule==0.3.*
